/*
* generated by Xtext
*/
package com.ms.qaTools.saturn.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class KronusAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/ms/qaTools/saturn/parser/antlr/internal/InternalKronus.tokens");
	}
}
