/*
* generated by Xtext
*/
package com.ms.qaTools.saturn.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.ms.qaTools.saturn.services.KronusGrammarAccess;

public class KronusParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private KronusGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.ms.qaTools.saturn.parser.antlr.internal.InternalKronusParser createParser(XtextTokenStream stream) {
		return new com.ms.qaTools.saturn.parser.antlr.internal.InternalKronusParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TopLevelKronus";
	}
	
	public KronusGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(KronusGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
