/**
 * generated by Xtext
 */
package com.ms.qaTools.saturn.validation;

import com.ms.qaTools.saturn.validation.AbstractKronusValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class KronusValidator extends AbstractKronusValidator {
}
