/*
* generated by Xtext
*/
package com.ms.qaTools.saturn;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class KronusStandaloneSetup extends KronusStandaloneSetupGenerated{

	public static void doSetup() {
		new KronusStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

