/*
 * generated by Xtext
 */
package com.ms.qaTools.saturn.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractKronusValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.ms.qaTools.saturn.kronus.KronusPackage.eINSTANCE);
		return result;
	}
}
