/*
 * generated by Xtext
 */
package com.ms.qaTools.saturn.validation

// Template from which eclipse/com.ms.qaTools.saturn.kronus/xtend-gen/com/ms/qaTools/saturn/validation/KronusValidator.java is generated, do not remove.

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class KronusValidator extends AbstractKronusValidator {}
